In [29]:
#Imporitng the dataset

import pandas as pd
import numpy as np

url ="https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"

df = pd.read_csv(url, header = None)

In [5]:
df.head(5)

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       205 non-null    int64
 1   1       205 non-null    object
 2   2       205 non-null    object
 3   3       205 non-null    object
 4   4       205 non-null    object
 5   5       205 non-null    object
 6   6       205 non-null    object
 7   7       205 non-null    object
 8   8       205 non-null    object
 9   9       205 non-null    float64
 10  10      205 non-null    float64
 11  11      205 non-null    float64
 12  12      205 non-null    float64
 13  13      205 non-null    int64
 14  14      205 non-null    object
 15  15      205 non-null    object
 16  16      205 non-null    int64
 17  17      205 non-null    object
 18  18      205 non-null    object
 19  19      205 non-null    object
 20  20      205 non-null    float64
 21  21      205 non-null    object
 22  22      205 non-null    object
 23  23      205 non-null    int64
 24  24      205 non-null    int64
 25  25      205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [17]:
url2 = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/misc"

df2 = pd.read_csv(url2, header = None, sep = '\n')

In [18]:
df2.head()

                                                   0
0                        Wants: width and horsepower
1                                             1 fast
2                                             1 slow
3    2nd fast must be highly similar to width of ...
4                                 dodge\t\t64.60\t88

In [20]:
print(df[25])

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: 25, Length: 205, dtype: object

In [30]:
bins = np.linspace(min(df[25]),max(df[25]), 4)

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

In [34]:
df[25] = df[25].astype('int32', copy = False )

ValueError: invalid literal for int() with base 10: '?'